### ISSUE TITLE
About upsampling

### ISSUE THREAD

**Issue by jdavidd** [SleyAI/Biomedical-Segmentation-with-PyTorch#1]
Hello.
I see that you said you wanted to learn the umsampling layers, but i dont see were you sset param.require_grad() = false, this means you learned them?
I have like 3k images with brain tumors, i have a FCN8s net and i managed to obtain 50% IOU accuracy, and with a unet 60% Dice. I see that you obtain more. Can I use your net, and do you have thet weigths sa I can make transfer learning?
PS. You can use google colab, where you have 15GB gpu memory for free

**Comment by SleyAI** [comment]
Hello,
yes I learned the upsampling layers. The status of this project is not up to date at all, I'm a bit sloppy with that. I finished my bachelor thesis with good results (U-Net was by far the best though) but I didn't update this repo. It's definitely on my todo list but I don't know when I will have time for that. I will check if I still have my models. I did transfer learning aswell. Of course you can use my net :)
